spring:
  application:
    name: event-validation-api
  main:
    web-application-type: reactive
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
webhooks:
  dynamodb:
    table-name: event_schema
    cache-ttl: PT5M
  kafka:
    bootstrap-servers: localhost:9092
    ingress-topic-prefix: wh.ingress
logging:
  level:
    root: INFO
    com.java.barclaycardus.webhooksvcs.pubsrc: DEBUG
